on: [push]

permissions: write-all

jobs:
  hello_wizard:
    runs-on: ubuntu-latest
    name: YOU SHALL NOT PASS!
    steps:
      - name: Setup Python
        if: always()
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Set up grading environment
        run: |
          sudo apt-get update
          sudo python -m pip install --upgrade pip
          sudo python -m pip install gatorgrade --ignore-installed PyYAML
      - name: Checkout
        uses: actions/checkout@v2
        with: 
         fetch-depth: '0'
      - name: Grade
        id: grade
        run: |
          gatorgrade --config .gatorgrade.yml
        if: always()
        env:
          PIPENV_VENV_IN_PROJECT: 1
          PIPENV_IGNORE_VIRTUALENVS: 1
      - name: WIIIIIZARRDDDD
        id: wizard
        uses: term-world/wizard@v0.2.6
        if: always()
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
